/*
*   Code By Michael Sherif Naguib
*   Started September 29, 2018
*   Studying @ University of Tulsa
* */
var express = require('express');
var router = express.Router();

/*
* Title: generateTest
* Description: accepts parameters for generating a random test as a json object, validates the object to make sure it
*              meets base requirements, a test is generated by 'an algorithim' and sends back specific question data as a
*              list of objects and responds with an error otherwise.
* */
router.get('/', function(req, res, next) {
    res.send('respond with a resource');
});

module.exports = router;